---
# Configuration Minikube
minikube_cpus: 2
minikube_memory: "4096"
minikube_driver: "docker"

# Configuration MetalLB
metallb_ip_range: "192.168.49.100-192.168.49.200"

# Configuration application
app_namespace: "notesapp"

# Images Docker (utiliser les images Minikube)
frontend_image: "notes-frontend:latest"
backend_image: "notes-api:latest"

# Versions des outils
kubectl_version: "stable"
terraform_version: "1.5.7"
helm_version: "3.12.3"
